//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddressBookManagerDomain.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail_template
    {
        public string name { get; set; }
        public string subject { get; set; }
        public string body { get; set; }
    }
}
