//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddressBookManagerDomain.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class normal_user
    {
        public int user_id { get; set; }
        public int generation { get; set; }
        public string family_name { get; set; }
        public string given_name { get; set; }
        public string logon_id { get; set; }
        public Nullable<int> age { get; set; }
    }
}
